services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    image: sadaka_app:latest
    working_dir: /app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
    ports:
      - "8010:8000"
    env_file:
      - .env
    depends_on:
      - redis
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    restart: unless-stopped

  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile
    image: sadaka_app:latest
    working_dir: /app
    command: celery -A app.celery_app:celery_app worker --loglevel=info
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis
    restart: unless-stopped

  celery_beat:
    build:
      context: .
      dockerfile: Dockerfile
    image: sadaka_app:latest
    working_dir: /app
    command: celery -A app.celery_app:celery_app beat --loglevel=info
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis
    restart: unless-stopped

  flower:
    build:
      context: .
      dockerfile: Dockerfile
    image: sadaka_app:latest
    working_dir: /app
    command: celery -A app.celery_app:celery_app flower --address=0.0.0.0 --port=5555
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      FLOWER_BASIC_AUTH: ${FLOWER_BASIC_AUTH:-}
      FLOWER_MAX_TASKS: ${FLOWER_MAX_TASKS:-10000}
    ports:
      - "5557:5555"
    depends_on:
      - redis
    restart: unless-stopped
