"""User__phone

Revision ID: ca0f1fa6d736
Revises: f88841f79d03
Create Date: 2025-08-23 10:55:32.191061

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ca0f1fa6d736"
down_revision: Union[str, None] = "f88841f79d03"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "onetimepasss",
        sa.Column("phone", sa.String(length=12), nullable=True),
        sa.Column("code", sa.String(length=6), nullable=True),
        sa.Column("expiration", sa.DateTime(), nullable=True),
        sa.Column("count_of_request", sa.Integer(), nullable=False),
        sa.Column("count_of_confirmation", sa.Integer(), nullable=False),
        sa.Column("blocked_requests_until", sa.DateTime(), nullable=True),
        sa.Column("blocked_confirmations_until", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("phone"),
    )
    op.create_foreign_key(None, "funds", "regions", ["region_id"], ["id"])
    op.add_column("users", sa.Column("phone", sa.String(length=11), nullable=True))
    op.alter_column("users", "name", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("users", "email", existing_type=sa.VARCHAR(), nullable=True)
    op.create_unique_constraint(None, "users", ["phone"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="unique")
    op.alter_column("users", "email", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("users", "name", existing_type=sa.VARCHAR(), nullable=False)
    op.drop_column("users", "phone")
    op.drop_constraint(None, "funds", type_="foreignkey")
    op.drop_table("onetimepasss")
    # ### end Alembic commands ###
