"""fk tables

Revision ID: 55e56381edfc
Revises: e9142a3a3399
Create Date: 2025-10-08 11:53:04.597005

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "55e56381edfc"
down_revision: Union[str, None] = "e9142a3a3399"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "onetimepasss",
        sa.Column("phone", sa.String(length=12), nullable=True),
        sa.Column("code", sa.String(length=6), nullable=True),
        sa.Column("expiration", sa.DateTime(), nullable=True),
        sa.Column("count_of_request", sa.Integer(), nullable=False),
        sa.Column("count_of_confirmation", sa.Integer(), nullable=False),
        sa.Column("blocked_requests_until", sa.DateTime(), nullable=True),
        sa.Column("blocked_confirmations_until", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_onetimepasss")),
        sa.UniqueConstraint("phone", name=op.f("uq_onetimepasss_phone")),
    )
    op.create_table(
        "comments",
        sa.Column("content", sa.String(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], name=op.f("fk_comments_project_id_projects")),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_comments_user_id_users")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_comments")),
    )
    op.create_index(op.f("ix_comments_project_id"), "comments", ["project_id"], unique=False)
    op.create_index(op.f("ix_comments_user_id"), "comments", ["user_id"], unique=False)
    op.create_table(
        "user_fund_access",
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("fund_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["fund_id"], ["funds.id"], name=op.f("fk_user_fund_access_fund_id_funds")),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_user_fund_access_user_id_users")),
    )
    op.create_index(op.f("ix_user_fund_access_fund_id"), "user_fund_access", ["fund_id"], unique=False)
    op.create_index(op.f("ix_user_fund_access_user_id"), "user_fund_access", ["user_id"], unique=False)
    op.create_table(
        "referral_referees",
        sa.Column("referral_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["referral_id"], ["referrals.id"], name=op.f("fk_referral_referees_referral_id_referrals")
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_referral_referees_user_id_users")),
        sa.PrimaryKeyConstraint("referral_id", "user_id", name=op.f("pk_referral_referees")),
    )
    op.create_index(op.f("ix_citys_region_id"), "citys", ["region_id"], unique=False)
    op.create_index(op.f("ix_files_fund_document_id"), "files", ["fund_document_id"], unique=False)
    op.create_index(op.f("ix_files_project_document_id"), "files", ["project_document_id"], unique=False)
    op.create_index(op.f("ix_files_project_picture_id"), "files", ["project_picture_id"], unique=False)
    op.create_index(op.f("ix_files_stage_id"), "files", ["stage_id"], unique=False)
    op.create_index(op.f("ix_funds_region_id"), "funds", ["region_id"], unique=False)
    op.create_index(op.f("ix_payments_project_id"), "payments", ["project_id"], unique=False)
    op.create_index(op.f("ix_payments_provider"), "payments", ["provider"], unique=False)
    op.create_index(op.f("ix_payments_referral_id"), "payments", ["referral_id"], unique=False)
    op.create_index(op.f("ix_payments_stage_id"), "payments", ["stage_id"], unique=False)
    op.create_index(op.f("ix_payments_status"), "payments", ["status"], unique=False)
    op.create_index(op.f("ix_payments_user_id"), "payments", ["user_id"], unique=False)
    op.create_index(op.f("ix_projects_fund_id"), "projects", ["fund_id"], unique=False)
    op.create_index(op.f("ix_projects_status"), "projects", ["status"], unique=False)
    op.create_index(op.f("ix_referrals_fund_id"), "referrals", ["fund_id"], unique=False)
    op.create_index(op.f("ix_referrals_project_id"), "referrals", ["project_id"], unique=False)
    op.create_index(op.f("ix_referrals_sharer_id"), "referrals", ["sharer_id"], unique=False)
    op.create_index(op.f("ix_regions_country_id"), "regions", ["country_id"], unique=False)
    op.create_index(op.f("ix_stages_project_id"), "stages", ["project_id"], unique=False)
    op.create_index(op.f("ix_users_city_id"), "users", ["city_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_city_id"), table_name="users")
    op.drop_index(op.f("ix_stages_project_id"), table_name="stages")
    op.drop_index(op.f("ix_regions_country_id"), table_name="regions")
    op.drop_index(op.f("ix_referrals_sharer_id"), table_name="referrals")
    op.drop_index(op.f("ix_referrals_project_id"), table_name="referrals")
    op.drop_index(op.f("ix_referrals_fund_id"), table_name="referrals")
    op.drop_index(op.f("ix_projects_status"), table_name="projects")
    op.drop_index(op.f("ix_projects_fund_id"), table_name="projects")
    op.drop_index(op.f("ix_payments_user_id"), table_name="payments")
    op.drop_index(op.f("ix_payments_status"), table_name="payments")
    op.drop_index(op.f("ix_payments_stage_id"), table_name="payments")
    op.drop_index(op.f("ix_payments_referral_id"), table_name="payments")
    op.drop_index(op.f("ix_payments_provider"), table_name="payments")
    op.drop_index(op.f("ix_payments_project_id"), table_name="payments")
    op.drop_index(op.f("ix_funds_region_id"), table_name="funds")
    op.drop_index(op.f("ix_files_stage_id"), table_name="files")
    op.drop_index(op.f("ix_files_project_picture_id"), table_name="files")
    op.drop_index(op.f("ix_files_project_document_id"), table_name="files")
    op.drop_index(op.f("ix_files_fund_document_id"), table_name="files")
    op.drop_index(op.f("ix_citys_region_id"), table_name="citys")
    op.drop_table("referral_referees")
    op.drop_index(op.f("ix_user_fund_access_user_id"), table_name="user_fund_access")
    op.drop_index(op.f("ix_user_fund_access_fund_id"), table_name="user_fund_access")
    op.drop_table("user_fund_access")
    op.drop_index(op.f("ix_comments_user_id"), table_name="comments")
    op.drop_index(op.f("ix_comments_project_id"), table_name="comments")
    op.drop_table("comments")
    op.drop_table("onetimepasss")
    # ### end Alembic commands ###
