"""user__phone_12_chars

Revision ID: 047eb2913ed0
Revises: ca0f1fa6d736
Create Date: 2025-08-23 17:39:28.789974

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "047eb2913ed0"
down_revision: Union[str, None] = "ca0f1fa6d736"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users", "phone", existing_type=sa.VARCHAR(length=11), type_=sa.String(length=12), existing_nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users", "phone", existing_type=sa.String(length=12), type_=sa.VARCHAR(length=11), existing_nullable=True
    )
    # ### end Alembic commands ###
