"""referral

Revision ID: 44c8a8c16cb9
Revises: ed8ff416b60d
Create Date: 2025-09-03 11:11:33.646440

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "44c8a8c16cb9"
down_revision: Union[str, None] = "ed8ff416b60d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "referrals",
        sa.Column("entity_type", sa.Enum("JOIN", "FUND", "PROJECT", name="referraltypeenum"), nullable=False),
        sa.Column("entity_id", sa.Integer(), nullable=True),
        sa.Column("key", sa.String(length=6), nullable=False),
        sa.Column("sharer_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["sharer_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("key"),
    )
    op.add_column("payments", sa.Column("referral_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "payments", "referrals", ["referral_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "payments", type_="foreignkey")
    op.drop_column("payments", "referral_id")
    op.drop_table("referrals")
    # ### end Alembic commands ###
