"""referral relations

Revision ID: 28e0b299b2e6
Revises: 156c69e70d07
Create Date: 2025-09-11 17:22:47.377676

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "28e0b299b2e6"
down_revision: Union[str, None] = "156c69e70d07"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "referral_referees",
        sa.Column("referral_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["referral_id"], ["referrals.id"], name=op.f("fk_referral_referees_referral_id_referrals")
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_referral_referees_user_id_users")),
        sa.PrimaryKeyConstraint("referral_id", "user_id", name=op.f("pk_referral_referees")),
    )
    op.drop_constraint("citys_name_key", "citys", type_="unique")
    op.create_unique_constraint(op.f("uq_citys_name"), "citys", ["name"])
    op.drop_constraint("countrys_name_key", "countrys", type_="unique")
    op.create_unique_constraint(op.f("uq_countrys_name"), "countrys", ["name"])
    op.drop_constraint("funds_picture_id_key", "funds", type_="unique")
    op.create_unique_constraint(op.f("uq_funds_picture_id"), "funds", ["picture_id"])
    op.drop_constraint("onetimepasss_phone_key", "onetimepasss", type_="unique")
    op.create_unique_constraint(op.f("uq_onetimepasss_phone"), "onetimepasss", ["phone"])
    op.add_column("referrals", sa.Column("fund_id", sa.Integer(), nullable=True))
    op.add_column("referrals", sa.Column("project_id", sa.Integer(), nullable=True))
    op.drop_constraint("referrals_key_key", "referrals", type_="unique")
    op.create_unique_constraint(op.f("uq_referrals_key"), "referrals", ["key"])
    op.create_foreign_key(op.f("fk_referrals_project_id_projects"), "referrals", "projects", ["project_id"], ["id"])
    op.create_foreign_key(op.f("fk_referrals_fund_id_funds"), "referrals", "funds", ["fund_id"], ["id"])
    op.drop_column("referrals", "entity_id")
    op.drop_constraint("regions_name_key", "regions", type_="unique")
    op.drop_constraint("regions_picture_id_key", "regions", type_="unique")
    op.create_unique_constraint(op.f("uq_regions_name"), "regions", ["name"])
    op.create_unique_constraint(op.f("uq_regions_picture_id"), "regions", ["picture_id"])
    op.drop_constraint("users_email_key", "users", type_="unique")
    op.drop_constraint("users_phone_key", "users", type_="unique")
    op.drop_constraint("users_picture_id_key", "users", type_="unique")
    op.create_unique_constraint(op.f("uq_users_email"), "users", ["email"])
    op.create_unique_constraint(op.f("uq_users_phone"), "users", ["phone"])
    op.create_unique_constraint(op.f("uq_users_picture_id"), "users", ["picture_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_users_picture_id"), "users", type_="unique")
    op.drop_constraint(op.f("uq_users_phone"), "users", type_="unique")
    op.drop_constraint(op.f("uq_users_email"), "users", type_="unique")
    op.create_unique_constraint("users_picture_id_key", "users", ["picture_id"])
    op.create_unique_constraint("users_phone_key", "users", ["phone"])
    op.create_unique_constraint("users_email_key", "users", ["email"])
    op.drop_constraint(op.f("uq_regions_picture_id"), "regions", type_="unique")
    op.drop_constraint(op.f("uq_regions_name"), "regions", type_="unique")
    op.create_unique_constraint("regions_picture_id_key", "regions", ["picture_id"])
    op.create_unique_constraint("regions_name_key", "regions", ["name"])
    op.add_column("referrals", sa.Column("entity_id", sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(op.f("fk_referrals_fund_id_funds"), "referrals", type_="foreignkey")
    op.drop_constraint(op.f("fk_referrals_project_id_projects"), "referrals", type_="foreignkey")
    op.drop_constraint(op.f("uq_referrals_key"), "referrals", type_="unique")
    op.create_unique_constraint("referrals_key_key", "referrals", ["key"])
    op.drop_column("referrals", "project_id")
    op.drop_column("referrals", "fund_id")
    op.drop_constraint(op.f("uq_onetimepasss_phone"), "onetimepasss", type_="unique")
    op.create_unique_constraint("onetimepasss_phone_key", "onetimepasss", ["phone"])
    op.drop_constraint(op.f("uq_funds_picture_id"), "funds", type_="unique")
    op.create_unique_constraint("funds_picture_id_key", "funds", ["picture_id"])
    op.drop_constraint(op.f("uq_countrys_name"), "countrys", type_="unique")
    op.create_unique_constraint("countrys_name_key", "countrys", ["name"])
    op.drop_constraint(op.f("uq_citys_name"), "citys", type_="unique")
    op.create_unique_constraint("citys_name_key", "citys", ["name"])
    op.drop_table("referral_referees")
    # ### end Alembic commands ###
