"""index

Revision ID: 3d3a2956b2d0
Revises: 0e47f4a204cf
Create Date: 2025-09-20 11:05:48.128384

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3d3a2956b2d0"
down_revision: Union[str, None] = "0e47f4a204cf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_citys_region_id"), "citys", ["region_id"], unique=False)
    op.create_index(op.f("ix_comments_project_id"), "comments", ["project_id"], unique=False)
    op.create_index(op.f("ix_comments_user_id"), "comments", ["user_id"], unique=False)
    op.create_index(op.f("ix_files_fund_document_id"), "files", ["fund_document_id"], unique=False)
    op.create_index(op.f("ix_files_project_document_id"), "files", ["project_document_id"], unique=False)
    op.create_index(op.f("ix_files_project_picture_id"), "files", ["project_picture_id"], unique=False)
    op.create_index(op.f("ix_files_stage_id"), "files", ["stage_id"], unique=False)
    op.create_index(op.f("ix_funds_region_id"), "funds", ["region_id"], unique=False)
    op.create_index(op.f("ix_payments_project_id"), "payments", ["project_id"], unique=False)
    op.create_index(op.f("ix_payments_referral_id"), "payments", ["referral_id"], unique=False)
    op.create_index(op.f("ix_payments_stage_id"), "payments", ["stage_id"], unique=False)
    op.create_index(op.f("ix_payments_status"), "payments", ["status"], unique=False)
    op.create_index(op.f("ix_payments_user_id"), "payments", ["user_id"], unique=False)
    op.create_index(op.f("ix_projects_fund_id"), "projects", ["fund_id"], unique=False)
    op.create_index(op.f("ix_projects_status"), "projects", ["status"], unique=False)
    op.create_index(op.f("ix_referrals_fund_id"), "referrals", ["fund_id"], unique=False)
    op.create_index(op.f("ix_referrals_project_id"), "referrals", ["project_id"], unique=False)
    op.create_index(op.f("ix_referrals_sharer_id"), "referrals", ["sharer_id"], unique=False)
    op.create_index(op.f("ix_regions_country_id"), "regions", ["country_id"], unique=False)
    op.create_index(op.f("ix_stages_project_id"), "stages", ["project_id"], unique=False)
    op.create_index(op.f("ix_user_fund_access_fund_id"), "user_fund_access", ["fund_id"], unique=False)
    op.create_index(op.f("ix_user_fund_access_user_id"), "user_fund_access", ["user_id"], unique=False)
    op.create_index(op.f("ix_users_city_id"), "users", ["city_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_city_id"), table_name="users")
    op.drop_index(op.f("ix_user_fund_access_user_id"), table_name="user_fund_access")
    op.drop_index(op.f("ix_user_fund_access_fund_id"), table_name="user_fund_access")
    op.drop_index(op.f("ix_stages_project_id"), table_name="stages")
    op.drop_index(op.f("ix_regions_country_id"), table_name="regions")
    op.drop_index(op.f("ix_referrals_sharer_id"), table_name="referrals")
    op.drop_index(op.f("ix_referrals_project_id"), table_name="referrals")
    op.drop_index(op.f("ix_referrals_fund_id"), table_name="referrals")
    op.drop_index(op.f("ix_projects_status"), table_name="projects")
    op.drop_index(op.f("ix_projects_fund_id"), table_name="projects")
    op.drop_index(op.f("ix_payments_user_id"), table_name="payments")
    op.drop_index(op.f("ix_payments_status"), table_name="payments")
    op.drop_index(op.f("ix_payments_stage_id"), table_name="payments")
    op.drop_index(op.f("ix_payments_referral_id"), table_name="payments")
    op.drop_index(op.f("ix_payments_project_id"), table_name="payments")
    op.drop_index(op.f("ix_funds_region_id"), table_name="funds")
    op.drop_index(op.f("ix_files_stage_id"), table_name="files")
    op.drop_index(op.f("ix_files_project_picture_id"), table_name="files")
    op.drop_index(op.f("ix_files_project_document_id"), table_name="files")
    op.drop_index(op.f("ix_files_fund_document_id"), table_name="files")
    op.drop_index(op.f("ix_comments_user_id"), table_name="comments")
    op.drop_index(op.f("ix_comments_project_id"), table_name="comments")
    op.drop_index(op.f("ix_citys_region_id"), table_name="citys")
    # ### end Alembic commands ###
