"""payment provider info

Revision ID: 6316756f7b40
Revises: 3d3a2956b2d0
Create Date: 2025-10-07 10:24:43.683418

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6316756f7b40"
down_revision: Union[str, None] = "3d3a2956b2d0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "payments", sa.Column("provider", sa.Enum("YOOKASSA", "TBANK", name="payment_provider_enum"), nullable=False)
    )
    op.add_column("payments", sa.Column("provider_payment_id", sa.String(), nullable=False))
    op.alter_column(
        "payments", "id", existing_type=sa.UUID(), type_=sa.Integer(), existing_nullable=False, autoincrement=True
    )
    op.create_index(op.f("ix_payments_provider"), "payments", ["provider"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_payments_provider"), table_name="payments")
    op.alter_column(
        "payments", "id", existing_type=sa.Integer(), type_=sa.UUID(), existing_nullable=False, autoincrement=True
    )
    op.drop_column("payments", "provider_payment_id")
    op.drop_column("payments", "provider")
    # ### end Alembic commands ###
